language: bash

before_install:
    - echo "deb http://archive.ubuntu.com/ubuntu/ precise main restricted" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    # failed packages
    # epubcheck
    - sudo apt-get install -y autotools-dev checkbot dia ghostscript imagemagick inkscape poppler-utils transfig
    - sudo apt-get install -y python-libxml2 python-lxml libimage-exiftool-perl 
    - sudo apt-get-install -y libxml2-utils libxslt1.1 xsltproc libxml2 xmlstarlet sgml-base sgml-data
    - sudo apt-get install -y jing docbook docbook-xml docbook5-xml docbook-xslt libxml-commons-external-java libxmlgraphics-commons-java fop remake w3m xfig

install:
    # - ./configure && make install
    - echo '*** install: ./configure && make install'
    - cat /etc/apt/sources.list

script:
    # - make test
    - echo '*** script: make test'
